---
- name: Remove and then copy authkeys for multiple users
  hosts: all
  remote_user: ansible_user
  become: yes
  become_method: sudo
  
  tasks:
  - name: Remove current authkey file
    authorized_key:
      user: "{{ item }}"
      state: present
    loop:
    - username1
    - username2
    
  - name: Set authorized key took from file
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', 'pubkeys/{{ item }}.pub') }}"
    loop:
    - username1
    - username2
...