---
- name: Copy the Ansible user's pubkeys from its own .ssh file to remote
  hosts: all
  remote_user: ansible_user
  become: yes
  become_method: sudo
  
  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: ansible_user
      state: present
      key: "{{ lookup('file', '/home/ansible_user/.ssh/id_rsa.pub') }}"
...