---
- name: Create new nonwheel users with authkeys
  hosts: all
  remote_user: ansible_user
  become: yes
  become_method: sudo
  
  vars:
    usernames:
      - username1
      - username2
    passwords:
      - '$6$rounds: 656000$4lIYx7DL2AKRyR4S$GJqDsT0jlHmdB2D6vtAVGS4O5VmmhEBWxu21a.dSpbRF9ajsosoO4mHbRfdgeuzPmWPXhe9gITiUfAC2/uxCW1'

  tasks:
  - name: Create group
    group: 
      name: groupname
      state: present
    
  - name: Create users
    user: 
      name: "{{ usernames }}"
      state: present 
      password: "{{ passwords }}"
      shell: '/bin/bash'
      append: yes 
      groups: devs
    loop:
      name: "{{ usernames }}"
      pass: "{{ passwords }}"

    # created with
    # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
    
  - name: Expire account
    command: "chage -I 30 -M 60 {{  item  }}"
    loop: "{{ usernames }}"
    
  - name: Set authorized key took from file
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', 'pubkeys/{{ item }}.pub') }}"
    loop:
    - username1
    - username2
...