---
- name: Remove authkeys for multiple users
  hosts: all
  remote_user: ansible_user
  become: yes
  become_method: sudo
    
  tasks:
  - name: Remove keys for multiple users
    authorized_key:
      user: "{{ item }}"
      state: absent
    loop:
    - username1
    - username2
...