---
- name: "RHEL 7 CIS 1.1.1.1 - The cramfs filesystem type is a compressed read-only Linux filesystem embedded in small footprint systems. A cramfs image can be used without having to first decompress the image."
  hosts: rhel
  gather_facts: no
  #remote_user: "{{ ansible_rhel_user }}"
  
  tasks:
  - name: Check to see if cramfs is loaded
    shell: ls -la /root
    register: lsmod_cramfs
    failed_when: lsmod_cramfs.stdout == 1

  - debug:
      msg: "{{ lsmod_cramfs.stdout_lines }}"
...