---
- name: "1.1.1 Disable unused filesystems"
  hosts: rhel
  
  tasks:
  - name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Automated)    
    lineinfile:
      create: true
      dest: /etc/modprobe.d/cramfs.conf
      regexp: cramfs
      line: install cramfs /bin/true
    check_mode: yes
    tags:
      - kernel_module_cramfs_disabled
      - low_severity
      - disable_strategy
      - low_complexity
      - medium_disruption
      - reboot_required
      - CCE-80137-3
      - NIST-800-53-CM-7(a)
      - NIST-800-53-CM-7(b)
      - NIST-800-53-CM-6(a)
      - NIST-800-171-3.4.6

  - name: 1.1.1.2 Ensure mounting of squashfs filesystems is disabled (Automated) 
    lineinfile:
      create: true
      dest: /etc/modprobe.d/squashfs.conf
      regexp: squashfs
      line: install squashfs /bin/true
    check_mode: yes
    tags:
      - kernel_module_squashfs_disabled
      - low_severity
      - disable_strategy
      - low_complexity
      - medium_disruption
      - reboot_required
      - CCE-80142-3
      - NIST-800-53-CM-7(a)
      - NIST-800-53-CM-7(b)
      - NIST-800-53-CM-6(a)
      - NIST-800-171-3.4.6

  - name: 1.1.1.3 Ensure mounting of udf filesystems is disabled (Automated) 
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.1.4 Ensure mounting of FAT filesystems is limited (Manual)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.2 Ensure /tmp is configured (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.3 Ensure noexec option set on /tmp partition (Automated) 
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.4 Ensure nodev option set on /tmp partition (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.5 Ensure nosuid option set on /tmp partition (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.6 Ensure /dev/shm is configured (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.7 Ensure noexec option set on /dev/shm partition (Automated) 
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.8 Ensure nodev option set on /dev/shm partition (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.9 Ensure nosuid option set on /dev/shm partition (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.10 Ensure separate partition exists for /var (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.11 Ensure separate partition exists for /var/tmp (Automated) 
  - name: 1.1.12 Ensure noexec option set on /var/tmp partition (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.13 Ensure nodev option set on /var/tmp partition (Automated) 
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.14 Ensure nosuid option set on /var/tmp partition (Automated) 
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.15 Ensure separate partition exists for /var/log (Automated)
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.16 Ensure separate partition exists for /var/log/audit (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.17 Ensure separate partition exists for /home (Automated) 
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.18 Ensure nodev option set on /home partition (Automated) 
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.19 Ensure noexec option set on removable media partitions (Manual)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.20 Ensure nodev option set on removable media partitions (Manual)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.21 Ensure nosuid option set on removable media partitions (Manual)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.22 Ensure sticky bit is set on all world-writable directories (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.23 Disable Automounting (Automated)    
    check_mode: yes
    tags:
    - tag1
    - tag2

  - name: 1.1.24 Disable USB Storage (Automated) 
    check_mode: yes
    tags:
    - tag1
    - tag2
...