---
- name: "Playbook: Registering systems to Satellite"
  hosts: all
  remote_user: username
  become: yes
  become_method: sudo

  tasks:
  - name: Copy RHEL8 repo files
    copy:
      dest: /path/to/file
      content: |
        [name]
        name=
        baseurl=
        enabled=1
        gpgcheck=1
        gpgkey=

  - name: Install subscription-manager
    yum:
      name: subscription-manager
      state: present

  - name: Install Katello Consumer RPM
    yum:
      name: url
      state: present

  - name: Register system with Satellite
    redhat_subscription:
      state: present
      activationkey: 1-222333444
      org_id: 222333444
      pool: '^(Red Hat Enterprise Server|Red Hat Virtualization)$'