---
- name: ServiceNow - Create Ticket
  hosts: localhost
  connection: local
  environment: "{{ pl_proxy }}"

  tasks:
  - name: Include servicenow role and create_ticket task
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "This is a test opened by Ansible {{ ansible_date_time.iso8601 }}"
    register: new_incident

  - debug: 
      var: new_incident.record
...
