---
- name: Install RSA Agent
  hosts: all
  remote_user: awxsvc
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: Make the /var/ace directory
    file: 
      dest: /var/ace
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Copy sdconf.rec from git repo into /var/ace
    get_url:
      url: http://al1xvftsat01.gmssup.com/pulp/isos/Vendor_Support/Library/custom/VSE-COTS/NonRPMS/sd_pam.conf
      dest: /var/ace/sdconf.rec
      state: present
      owner: root
      group: root
      mode: '0644'

  - name: Copy sd_pam.conf from into /var/ace
    get_url:
      url: http://al1xvftsat01.gmssup.com/pulp/isos/Vendor_Support/Library/custom/VSE-COTS/NonRPMS/sdconf.rec
      dest: /etc/sd_pam.conf
      state: present
      owner: root
      group: root
      mode: '0644'

  - name: Unarchive sd_pam_agent.tar into /opt on remote and check for pam_securid.so
    unarchive:
     src: http://al1xvftsat01.gmssup.com/pulp/isos/Vendor_Support/Library/custom/VSE-COTS/NonRPMS/sd_pam_agent.tar
     dest: /opt
     creates: /opt/pam/lib/64bit/pam_securid.so
     owner: root
     group: root

  - name: Add auth sufficient pam_securid.so to /etc/pam.d/sshd
    lineinfile:
      path: /etc/pam.d/sshd
      line: "auth       sufficient   pam_securid.so"
      insertafter: '^\#\%PAM-1\.0'
      
  - name: Add auth sufficient pam_securid.so to /etc/sudo
    lineinfile:
      path: /etc/sudo
      line: "auth       sufficient   pam_securid.so"
      insertafter: '^\#\%PAM-1\.0'
  
  - name: Comment out auth       include      system-auth
    lineinfile:
      path: /etc/sudo
      regexp: '^auth\s.*include\s.*system-auth'
      state: present
      line: "#auth       sufficient   pam_securid.so"
  
  - name: Create a symlink to the pam_securid.so
    file:
      src: /opt/pam/lib/64bit/pam_securid.so
      dest: /lib64/security/pam_securid.so
      owner: root
      group: root
      state: link
...