---
- name: "RHEL 7 CIS 1.1.1.2 - The squashfs filesystem type is a compressed read-only Linux filesystem embedded in small footprint systems (similar to cramfs ). A squashfs image can be used without having to first decompress the image."
  hosts: rhel
  
  tasks:
  - name: Ensure kernel module 'squashfs' is disabled
    lineinfile:
      create: true
      dest: /etc/modprobe.d/squashfs.conf
      regexp: squashfs
      line: install squashfs /bin/true
    check_mode: yes
    tags:
      - kernel_module_squashfs_disabled
      - low_severity
      - disable_strategy
      - low_complexity
      - medium_disruption
      - reboot_required
      - CCE-80142-3
      - NIST-800-53-CM-7(a)
      - NIST-800-53-CM-7(b)
      - NIST-800-53-CM-6(a)
      - NIST-800-171-3.4.6
...