---
- name: Testing ServiceNow connectivity through proxy
  hosts: servicenow
  gather_facts: no
# connections:
# - servicenow.servicenow

  tasks:
  - name: Grab a user record
    snow_record:
      username: ansible_test
      password: my_password
      instance: paclifedev
      state: present
      table: sys_user
      lookup_field: sys_id
    environment:
        https_proxy: http://plproxy.pacificlife.net:8080
    
  - name: Search for incident assigned to group, return specific fields
    snow_record_find:
      username: ansible_test
      password: my_password
      instance: paclifedev
      table: incident
      query:
        assignment_group: d625dccec0a8016700a222a0f7900d06
      return_fields:
        - number
        - opened_at
...