---
- name: SHUTDOWN ALL SERVERS
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  collections:
  - community.general

  tasks:
  - name: ALL YOUR BASE ARE BELONG TO US
    shutdown:
...
