---
- hosts: all
  remote_user: ansible_user
  become: yes
  become_method: sudo
  
- tasks:
  - name: Adding username back to wheel
    user: name={{  item  }} state=present groups=wheel
    with_items:
    - username1
    - username2
...