---
- hosts: all
  remote_user: username
  become: yes
  become_method: sudo

- tasks:
  - name: Delete the old groupname group 
    group: name=groupname state=absent
  
  - name: Add groupname group
    group: name=groupname state=present
  
  - name: Add the username guys to groupname group
    user: name={{  item  }} state=present groups=groupname 
    with_items:
    - username1
    - username2
    
  - name: Remove line with miriumwheel in it
    lineinfile: dest=/etc/sudoers state=absent regexp="groupname"
  
  - name: Add a new line with comment
    lineinfile: "dest=/etc/sudoers state=present line='#Adding the groupname group for the username SysAdmins'"
  
  - name: Adding groupname line
    lineinfile: "dest=/etc/sudoers state=present line='%groupname  ALL=(ALL)       ALL'"
...