---
- hosts: all
  remote_user: ansible_user
  become: yes
  become_method: sudo

- tasks:
  - name: Check usernames
    command: grep username /etc/passwd
    register: wheel
  
  - debug: var=wheel.stdout_lines
...