#!/bin/bash
export KEY="<keyhere>"
export PASS="<password>"

### Fun Sutff Begins Here ###
/usr/bin/expect <<EOD
spawn ssh -o "StrictHostKeyChecking=no" $1
expect "Password:"
send "$PASS\n"
expect ">"
send "echo $KEY >> /home/something/.ssh/authorized_keys\n"
expect ">"
send "exit\n"
EOD