---
- hosts: all
  remote_user: username
  become: yes
  become_method: sudo

- tasks:
  - name: Create users
    user: name={{  item.name  }} state=present groups=miriumwheel password={{  item.pass  }}  shell='/bin/bash'
    with_items:
    - { name: 'username' , pass: '$6$rounds=656000$W.VLdMEi0VbKVxBL$Mmwa1Fz6VDeasKnbXhcUb8RTMCoBXIzkzlAT.gdAR3kHBjGaLB7Mu1Ba8wbPg5EvMRKbcKzKkYP6UiaP.u.pq0' }
    # created with
    # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
  
  - name: Expire account
    command: "chage -I 30 -M 60 {{  item  }}"
    with_items:
    - username1
    - username2
  
  - name: Create .ssh directory
    file: path=/home/{{  item  }}/.ssh/ state=directory mode=0700 owner={{  item  }} group={{  item  }}
    with_items:
    - username1
    - username2
  
  - name: Copy authkeys to .ssh dirs
    copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0700
    with_items:
    - username1
    - username2
...