---
- hosts: all
  remote_user: ansible_user
  become: yes
  become_method: sudo

- tasks:
  - name: Grant read only access to /var/log contents
    command: "setfacl -R -m u:username:r-- /var/log/"
...