---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Create users
          user: name={{  item.name  }} state=present password={{  item.pass  }}  shell='/bin/bash'
          with_items:
                 - { name: 'jlouthan' , pass: '$6$rounds=656000$DWIQ3lYfVJk8qoDT$Qu5c0lrElKhMnKE.ePJdk8.Pd6axtFJnWAXQ9rvPiK9RCTx8WSolZboqHgoOScMS7QJ54374GEQufgypejfTh0' }
