---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Add wheel group
        group: name=wheel state=present

      - name: Clean up mirumwheel group
        group: name=mirumwheel state=absent

      - name: Add the SysAdmins/Security to wheel group
        user: name={{  item  }} state=present groups=wheel
        with_items:
               - jlouthan
               - jbyers
               - jatkins
               - dhalliyur
               - secops

      - name: Adding wheel line to sudoers
        lineinfile: "dest=/etc/sudoers state=present line='%wheel  ALL=(ALL)       ALL'"
