---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Delete the old miriumwheel group 
        group: name=miriumwheel state=absent

      - name: Add mirumwheel group
        group: name=mirumwheel state=present

      - name: Add the Mirum guys to mirumwheel group
        user: name={{  item  }} state=present groups=mirumwheel 
        with_items:
               - bbeecroft
               - mhiivala
               - kchu
               - kmasud
               - rchavez

      - name: Remove line with miriumwheel in it
        lineinfile: dest=/etc/sudoers state=absent regexp="miriumwheel"

      - name: Add a new line with comment
        lineinfile: "dest=/etc/sudoers state=present line='#Adding the mirumwheel group for the Mirum SysAdmins'"

      - name: Adding mirumwheel line
        lineinfile: "dest=/etc/sudoers state=present line='%mirumwheel  ALL=(ALL)       ALL'"
