---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Unlock account
        command: passwd -u bwilliams

      - name: Expire account
        command: "chage -I 30 -M 60 -E -1 bwilliams"
