---
- hosts: ws1:test-automation
  remote_user: jlouthan
  become: yes
  become_method: sudo 

  tasks:
      - name: Adding mirumwheel group
        group: name=qa state=present

      - name: Add user to mirumwheel group
        user: name={{  item  }} groups=qa
        with_items:
         - erjimenez
         - amcdaniel
         - rmccoy
         - trodgers
         - erincon
         - srudra
