---
- hosts: vm6
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Create .ssh dirs
          file: path=/home/{{  item  }}/.ssh state=directory owner={{  item  }} group={{  item  }} mode=0700
          with_items:
            - bwilliams

        - name: Copy authkeys
          copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0600
          with_items:
            - bwilliams
