---
- hosts: web:db:internal
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
#        - name: Create group
#          group: name= state=present

        - name: Create users
          user: name={{  item.name  }} state=present password={{  item.pass  }}  shell='/bin/bash' append=yes groups=devs
          with_items:
                 - { name: 'ksain' , pass: '$6$rounds=656000$4lIYx7DL2AKRyR4S$GJqDsT0jlHmdB2D6vtAVGS4O5VmmhEBWxu21a.dSpbRF9ajsosoO4mHbRfdgeuzPmWPXhe9gITiUfAC2/uxCW1' }

        - name: Expire account
          command: "chage -I 30 -M 60 {{  item  }}"
          with_items:
            - ksain

        - name: Create .ssh directory
          file: path=/home/{{  item  }}/.ssh/ state=directory mode=0700 owner={{  item  }} group={{  item  }}
          with_items:
            - ksain

        - name: Copy authkeys to .ssh dirs
          copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0600
          with_items:
            - ksain
