---
- hosts: ws1:db
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
      - name: Create account
        user: name={{  item  }} shell=/bin/bash home=/home/bwilliams/
        with_items:
            - bwilliams

      - name: Expire account
        command: "chage -I 30 -M 60 bwilliams"

      - name: Create .ssh directory
        file: path=/home/{{  item  }}/.ssh/ state=directory mode=0700 owner={{  item  }} group={{  item  }}
        with_items:
            - bwilliams

      - name: Copy authkeys to .ssh dirs
        copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode=0700
        with_items:
            - bwilliams

      - name: Adding developer group
        group: name=developer state=present

      - name: Add user to developer group
        user: name={{  item  }} groups=developer
        with_items:
            - bwilliams
