---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo

  tasks:
        - name: Create .ssh directory
          file: path=/home/{{  item  }}/.ssh/ state=directory mode=0700 owner={{  item  }} group={{  item  }}
          with_items:
            - secops

        - name: Copy authkeys to .ssh dirs
          copy: src=authkeys/{{  item  }} dest=/home/{{  item  }}/.ssh/authorized_keys owner={{  item  }} group={{  item  }} mode="u+rwx,g-rwx,o-rwx"
          with_items:
            - secops
