---
- hosts: all
  remote_user: jlouthan
  become: yes
  become_method: sudo
  tasks:
      - name: Lock password (Note - this doesn't prevent SSHKey access)
        command: passwd -l {{ item }}
        with_items:
              - srudra

      - name: Expire account to Jan 2 1970 and remove from all secondary groups
        user: name={{ item }} expires=-1 groups=
        with_items:
              - srudra

      - name: Renaming authkeys file
        command: mv /home/{{ item }}/.ssh/authorized_keys /home/{{ item }}/.ssh/authorized_lock
        with_items:
              - srudra

#      - name: Remove keys
#        file: path=/home/{{ item }}/.ssh/authorized_keys state=absent
#        with_nydertems:
#              - chlangley
