---
- hosts: dbusmc:ws1
  remote_user: jlouthan
  become: yes
  become_method: sudo
  vars:
        # created with
        # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
        password: $6$rounds=656000$Bg027OpcRZfvRNEV$qn6C4L54qFZMc4WVMzjSW1qw0lTNzomwXUDD3gI2O6uW10VD7FY5YD9p5teXUzlCojCI8bov9uKKYMXC4IR4q/

  tasks:
      - name: Reset password
        user: name=jfargason password={{ password }}
