---
- hosts: all
  remote_user: ansible_user
  become: yes
  become_method: sudo

  tasks:
  - name: Add username to sudoers
    replace:
      path: /etc/sudoers
      regexp: 'name'
      replace: 'name1, name2'
      backup: yes
...