---
- hosts: all
  remote_user: username
  tasks:
      - name: Check usernames
        command: grep bahamat /etc/passwd
        register: wheel
        become: yes
        become_method: sudo

      - debug: var=wheel.stdout_lines
